cd agent/adk
GOOGLE_GENAI_USE_VERTEXAI=TRUE \
GOOGLE_CLOUD_PROJECT=<YOUR_PROJECT_ID> \
GOOGLE_CLOUD_LOCATION=<YOUR_REGION> \
GOOGLE_AGENT_ENGINE_ID=<AGENT_ENGINE_ID> \
GOOGLE_AGENT_ENGINE_LOCATION=<AGENT_ENGINE_LOCATION> \
GEMINI_MODEL_VERSION="gemini-live-2.5-flash-preview-native-audio" \
COACH_BACKEND_URL=http://localhost:8080 \
uvicorn main:app --host 0.0.0.0 --port 8000 --reload
